github_username: anugrahn1

title: skillz' writeups
email: pnanugrah@gmail.com
description: >- #CTF writeups for challenges that I like, I probably will focus on pwn more than other ctf categories. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anugrahn1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: jekyll/minima   #using remote theme doesn't let social media icons work
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
minima:
  skin: dark #dark mode for minima

defaults:
  - # this dash is needed or else the posts look weird
    scope:
      path: "" #which files to apply default values to 
      type: "posts" 
    values:
      #values
      layout: "post"
      author: "skillz"

github:
  repo: https://github.com/anugrahn1
